<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\Holidays\**" />
    <Compile Remove="Interfaces\Employee\**" />
    <Compile Remove="Services\EmployeeSer\**" />
    <EmbeddedResource Remove="DTOs\Holidays\**" />
    <EmbeddedResource Remove="Interfaces\Employee\**" />
    <EmbeddedResource Remove="Services\EmployeeSer\**" />
    <None Remove="DTOs\Holidays\**" />
    <None Remove="Interfaces\Employee\**" />
    <None Remove="Services\EmployeeSer\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Services\Attendances\BiometricService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\KPI\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
