using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// Rewritten to be fully idempotent (every operation guarded with an
    /// IF NOT EXISTS check) - EF's autogenerated version failed with
    /// "Column name 'FeatureName' in table 'ErrorLogs' is specified more
    /// than once" because ModuleName/FeatureName/some indexes on ErrorLogs
    /// (and possibly VerifyMode on BiometricAttendanceLogs, and the
    /// BiometricSyncLogs table itself) were already applied to this
    /// database directly via hand-run SQL scripts in an earlier session,
    /// without ever being captured as an EF migration - so EF's model diff
    /// against the last migration snapshot re-proposed them as new. Guarding
    /// every statement here makes this migration safe to run regardless of
    /// which of those were already applied, while still correctly bringing
    /// any environment that never ran those scripts fully up to date.
    /// </remarks>
    public partial class PendingMigrationEsslAttendanceSyncStates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.ErrorLogs') AND name = 'FeatureName')
    ALTER TABLE [dbo].[ErrorLogs] ADD [FeatureName] NVARCHAR(150) NULL;
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.ErrorLogs') AND name = 'ModuleName')
    ALTER TABLE [dbo].[ErrorLogs] ADD [ModuleName] NVARCHAR(150) NULL;
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricAttendanceLogs') AND name = 'VerifyMode')
    ALTER TABLE [dbo].[BiometricAttendanceLogs] ADD [VerifyMode] NVARCHAR(30) NULL;
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BiometricSyncLogs')
BEGIN
    CREATE TABLE [dbo].[BiometricSyncLogs] (
        [Id] NVARCHAR(450) NOT NULL,
        [TenantId] NVARCHAR(450) NOT NULL,
        [DeviceId] NVARCHAR(450) NULL,
        [AgentId] NVARCHAR(MAX) NULL,
        [SyncType] NVARCHAR(30) NOT NULL,
        [StartTime] DATETIME2 NOT NULL,
        [EndTime] DATETIME2 NULL,
        [RecordsFetched] INT NOT NULL,
        [RecordsInserted] INT NOT NULL,
        [RecordsSkipped] INT NOT NULL,
        [RecordsFailed] INT NOT NULL,
        [Status] NVARCHAR(20) NOT NULL,
        [ErrorMessage] NVARCHAR(500) NULL,
        [FromDate] DATETIME2 NULL,
        [ToDate] DATETIME2 NULL,
        [TriggeredBy] NVARCHAR(100) NULL,
        [IsDeleted] BIT NOT NULL,
        [CreatedOn] DATETIME2 NOT NULL,
        [CreatedBy] NVARCHAR(MAX) NOT NULL,
        [ModifiedOn] DATETIME2 NULL,
        [ModifiedBy] NVARCHAR(MAX) NULL,
        [IsActive] BIT NOT NULL,
        CONSTRAINT [PK_BiometricSyncLogs] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_BiometricSyncLogs_BiometricDevices_DeviceId] FOREIGN KEY ([DeviceId]) REFERENCES [dbo].[BiometricDevices]([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_BiometricSyncLogs_Tenants_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [dbo].[Tenants]([Id]) ON DELETE NO ACTION
    );
END
ELSE
BEGIN
    -- Table already existed (created by an earlier ad-hoc process before
    -- this feature had a real migration) - bring it up to date with both
    -- this feature's new columns AND any BaseEntity column it may be
    -- missing (e.g. IsActive), rather than assuming it already matches
    -- the current BaseEntity shape.
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'FromDate')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [FromDate] DATETIME2 NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'ToDate')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [ToDate] DATETIME2 NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'TriggeredBy')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [TriggeredBy] NVARCHAR(100) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'IsDeleted')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [IsDeleted] BIT NOT NULL CONSTRAINT DF_BiometricSyncLogs_IsDeleted DEFAULT (0);

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'IsActive')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [IsActive] BIT NOT NULL CONSTRAINT DF_BiometricSyncLogs_IsActive DEFAULT (1);

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'CreatedOn')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_BiometricSyncLogs_CreatedOn DEFAULT (SYSUTCDATETIME());

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'CreatedBy')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [CreatedBy] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_BiometricSyncLogs_CreatedBy DEFAULT ('System');

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'ModifiedOn')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [ModifiedOn] DATETIME2 NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricSyncLogs') AND name = 'ModifiedBy')
        ALTER TABLE [dbo].[BiometricSyncLogs] ADD [ModifiedBy] NVARCHAR(MAX) NULL;
END
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'EsslAttendanceSyncStates')
BEGIN
    CREATE TABLE [dbo].[EsslAttendanceSyncStates] (
        [Id] NVARCHAR(450) NOT NULL,
        [LastProcessedDeviceLogId] INT NULL,
        [LastProcessedLogDate] DATETIME2 NULL,
        [LastSyncStartedAt] DATETIME2 NULL,
        [LastSyncCompletedAt] DATETIME2 NULL,
        [LastSyncStatus] NVARCHAR(20) NULL,
        [LastError] NVARCHAR(1000) NULL,
        [RecordsRead] INT NOT NULL,
        [RecordsImported] INT NOT NULL,
        [RecordsSkipped] INT NOT NULL,
        [RecordsFailed] INT NOT NULL,
        [IsSyncRunning] BIT NOT NULL,
        [TenantId] NVARCHAR(450) NULL,
        [IsDeleted] BIT NOT NULL,
        [CreatedOn] DATETIME2 NOT NULL,
        [CreatedBy] NVARCHAR(MAX) NOT NULL,
        [ModifiedOn] DATETIME2 NULL,
        [ModifiedBy] NVARCHAR(MAX) NULL,
        [IsActive] BIT NOT NULL,
        CONSTRAINT [PK_EsslAttendanceSyncStates] PRIMARY KEY ([Id])
    );
END
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ErrorLogs_IsResolved' AND object_id = OBJECT_ID('dbo.ErrorLogs'))
    CREATE INDEX [IX_ErrorLogs_IsResolved] ON [dbo].[ErrorLogs]([IsResolved]);
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ErrorLogs_ModuleName' AND object_id = OBJECT_ID('dbo.ErrorLogs'))
    CREATE INDEX [IX_ErrorLogs_ModuleName] ON [dbo].[ErrorLogs]([ModuleName]);
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_BiometricSyncLogs_Device_StartTime' AND object_id = OBJECT_ID('dbo.BiometricSyncLogs'))
    CREATE INDEX [IX_BiometricSyncLogs_Device_StartTime] ON [dbo].[BiometricSyncLogs]([DeviceId], [StartTime]);
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_BiometricSyncLogs_Tenant_SyncType_StartTime' AND object_id = OBJECT_ID('dbo.BiometricSyncLogs'))
    CREATE INDEX [IX_BiometricSyncLogs_Tenant_SyncType_StartTime] ON [dbo].[BiometricSyncLogs]([TenantId], [SyncType], [StartTime]);
");

            migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EsslAttendanceSyncStates_Tenant' AND object_id = OBJECT_ID('dbo.EsslAttendanceSyncStates'))
    CREATE UNIQUE INDEX [IX_EsslAttendanceSyncStates_Tenant] ON [dbo].[EsslAttendanceSyncStates]([TenantId]) WHERE [TenantId] IS NOT NULL;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("IF OBJECT_ID('dbo.BiometricSyncLogs', 'U') IS NOT NULL DROP TABLE [dbo].[BiometricSyncLogs];");
            migrationBuilder.Sql("IF OBJECT_ID('dbo.EsslAttendanceSyncStates', 'U') IS NOT NULL DROP TABLE [dbo].[EsslAttendanceSyncStates];");

            migrationBuilder.Sql("IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ErrorLogs_IsResolved' AND object_id = OBJECT_ID('dbo.ErrorLogs')) DROP INDEX [IX_ErrorLogs_IsResolved] ON [dbo].[ErrorLogs];");
            migrationBuilder.Sql("IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ErrorLogs_ModuleName' AND object_id = OBJECT_ID('dbo.ErrorLogs')) DROP INDEX [IX_ErrorLogs_ModuleName] ON [dbo].[ErrorLogs];");

            migrationBuilder.Sql("IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.ErrorLogs') AND name = 'FeatureName') ALTER TABLE [dbo].[ErrorLogs] DROP COLUMN [FeatureName];");
            migrationBuilder.Sql("IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.ErrorLogs') AND name = 'ModuleName') ALTER TABLE [dbo].[ErrorLogs] DROP COLUMN [ModuleName];");
            migrationBuilder.Sql("IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BiometricAttendanceLogs') AND name = 'VerifyMode') ALTER TABLE [dbo].[BiometricAttendanceLogs] DROP COLUMN [VerifyMode];");
        }
    }
}
