using System;
using System.ComponentModel.DataAnnotations;
using static Domain.Enums.EnumExtensions;

namespace Domain.Entities
{
    // "System-detected, HR-approved" Comp Off candidate.
    // API/BackgroundServices/CompOffDetectionService.cs scans Attendance rows
    // and, when an employee worked >= AttendancePolicy.CompOffEligibleExtraHours
    // on a day that was a Holiday or WeekOff for their tenant, creates ONE of
    // these rows at Status = PendingReview - it never touches the employee's
    // leave balance itself. HR must individually review each candidate via
    // CompOffService.ApproveAsync (credits CreditedDays into the "Comp Off"
    // LeaveType balance via ILeaveBalanceService.CreditLeaveAsync) or
    // RejectAsync (no balance change) before anything is added.
    //
    // (EmployeeId, AttendanceId) is the idempotency key the detection job
    // checks before inserting a new row, so re-scanning the same Attendance
    // record on a later run (the job uses a rolling 7-day lookback window)
    // can never create a duplicate candidate for the same day.
    public class CompOffCandidate : BaseEntity
    {
        [Required]
        public string EmployeeId { get; set; }
        public virtual Employee Employee { get; set; }

        // The Attendance row that triggered detection.
        [Required]
        public string AttendanceId { get; set; }
        public virtual Attendance Attendance { get; set; }

        [Required]
        public DateTime WorkedDate { get; set; }

        // Hours actually worked on WorkedDate (Attendance.TotalWorkingHours) -
        // since WorkedDate is a Holiday/WeekOff there is no "expected" shift,
        // so every hour worked is voluntary/extra.
        public decimal HoursWorked { get; set; }

        // Short human-readable note generated by the detection job, e.g.
        // "Worked 5.5 hrs on Holiday: Diwali" / "Worked 6 hrs on Week Off".
        [MaxLength(500)]
        public string TriggerReason { get; set; }

        public CompOffCandidateStatus Status { get; set; } = CompOffCandidateStatus.PendingReview;

        // HR review (single-step: Approve or Reject) - see CompOffService.
        public string? ReviewedBy { get; set; }
        public DateTime? ReviewedOn { get; set; }

        [MaxLength(500)]
        public string? RejectionReason { get; set; }

        // How many Comp Off days were actually credited on approval - kept
        // simple by deliberate design decision: always exactly 1 full day
        // per eligible occurrence, no fractional comp-off math.
        public decimal CreditedDays { get; set; } = 1;

        public override string GetSequencePrefix() => "COFC";
    }
}
